#!/bin/bash
set -euo pipefail

cd /tmp/$KUDU

build-support/enable_devtoolset.sh thirdparty/build-if-necessary.sh

mkdir -p build/release
cd build/release
../../build-support/enable_devtoolset.sh \
      ../../thirdparty/installed/common/bin/cmake \
        -DCMAKE_BUILD_TYPE=release \
          ../..

make -j$PARALLEL

mkdir -p /app
cp bin/{kudu,kudu-tserver,kudu-master} /app
rsync -av --delete ../../www/ /app/www/ || true

